### ISSUE TITLE
Question in simulation.ipynb

### ISSUE THREAD

**Issue by vinngs1208** [Nickkontschak/Replication-The-virtue-of-complexity-in-machine-learning-portfolios#1]
Hi author, thanks for uploading your replication. Recently, I tried to run the simulation.ipynb but stuck at the backtest part. It appears TypeError: 'NoneType' object is not callable. I have checked the code and believe most of the function is correct to go. If possible, could you upload the metrics.parquet file for reference? many thanks~

**Comment by nkonts** [comment]
Hi, I have uploaded the `metrics.parquet` file and fixed the bug. It is a somewhat large since it includes every iteration for each combination of gamma, P, z, c and T and then repeat this 500 times to average out the randomness. 

When revising the code before uploading, it seems like that I had changed the backtest calculation from `Backtest.predict()` to `Backtest.performance()` for whatever reason which clashed with the attribute `Backtest.performance`.

**Comment by vinngs1208** [comment]
Dear author, big thanks for your timely response and the effort you put into resolving the issues I encountered while running the code on GitHub. Your assistance has been invaluable, and I greatly appreciate it. 

I am still studying the methodology mentioned in the paper, and hope to have further discussions with you in the future~
